### ISSUE TITLE
Make a prototype of product page (Nikolaj)

### ISSUE THREAD

**Issue by wivelsted** [Mercantec-GHC/projekt-gruppe2#3]
1.     Picture
2.     Description
3.     Price
4.     Add to cart
5.     Category (paper book, e-book, audiobook, new, used)
6.     Author

**Comment by nhave** [comment]
https://www.figma.com/design/d6AgAbpOYUIevTwKJQOAbU/Untitled?node-id=3-1583&t=UyG779BElYgU9sHJ-1
