### ISSUE TITLE
Create registration page.

### ISSUE THREAD

**Issue by nhave** [Mercantec-GHC/projekt-gruppe2#30]
The url is "/register"

**Comment by wivelsted** [comment]
Testing testing GitHub

**Comment by nhave** [comment]
Registrering er nu helt oppe at køre.

**Comment by nhave** [comment]
Registration har en fejl hvor der ikke bliver oprettet en bruger.

**Comment by nhave** [comment]
Fejl rettet, cache skal ryddes.
Username er nu tvunget til lowercase.
